title: Stress ball
hero_image: images/stress-banner.png
description: Use Scratch to create a stress ball that you can squash!
version: 4
listed: true
copyedit: true
last_tested: "2020-09-01"
steps:
  - title: Introduction
  - title: Add a Ball sprite
  - title: Add a face 
  - title: Squash it
  - title: Shrink it
  - title: Add a better sound effect
  - title: "Challenge: improve your stress ball"
  - title: Add a backdrop
  - title: "Challenge: improve your project"
  - title: What next?
